drop schema if exists sandbox cascade;

create schema sandbox;

/*
ingestion table
adapted from https://info.crunchydata.com/blog/fast-csv-and-json-ingestion-in-postgresql-with-copy
*/
create table sandbox.ingested_data
(
	id int generated by default as identity primary key,
	ingested_dt timestamp default current_timestamp,
	data jsonb not null,
	activity_loaded bool default false not null,
	streams_loaded bool default false not null
);

create index ingested_data_idx on sandbox.ingested_data using gin(data);

-- activity info table derived from ingested data
create table sandbox.activity
(
	activity_id bigint primary key,
	activity_name text,
	activity_type text,
	activity_start timestamptz,
	commute boolean,
	gear_id text,
	friend_count int,
	pr_count int,
	achieve_count int,
	total_energy numeric
)

-- activity streams
create table sandbox.streams
(
	activity_id bigint references sandbox.activity(activity_id),
	seconds_from_start int,
	moving boolean,
	elevation numeric,
	shape geography --srid 4326
);